"""Interdit toute trace de vocabulaire d'outil génératif dans les fichiers suivis.

Motif volontairement limité à trois catégories de vocabulaire GÉNÉRIQUE et
PUBLIC : noms de fournisseurs d'outils génératifs, formules de co-signature
automatique, formules d'attribution de génération. Aucun terme propre à la
nomenclature interne de ce projet (noms d'artefacts, de blocs, de lots, de
documents de transmission) n'y figure : un test qui énumérerait ce vocabulaire
interne serait lui-même la fuite qu'il prétend empêcher. La détection de ce
vocabulaire interne reste une revue manuelle, plus large, exécutée avant
chaque publication — ce test-ci est un filet permanent, pas un remplacement.

Ce fichier est nécessairement exclu de son propre parcours : il contient les
motifs recherchés en tant que données, pas en tant que trace.
"""

import subprocess
from pathlib import Path

RACINE = Path(__file__).resolve().parent.parent
CE_FICHIER = Path(__file__).resolve().relative_to(RACINE).as_posix()

MOTIFS_INTERDITS = [
    # Noms de fournisseurs d'outils génératifs
    "claude",
    "anthropic",
    "chatgpt",
    "openai",
    "gpt-3",
    "gpt-4",
    "gpt-5",
    "copilot",
    "gemini",
    "bard",
    "llama",
    "mistral ai",
    # Formules de co-signature automatique
    "co-authored-by",
    # Formules d'attribution de génération
    "generated by ai",
    "ai-generated",
    "ai generated",
    "ai-assisted",
    "ai assisted",
    "written by ai",
    "created with ai",
]


def fichiers_suivis() -> list[str]:
    sortie = subprocess.run(
        ["git", "-C", str(RACINE), "ls-files", "-z"],
        capture_output=True,
        check=True,
        text=True,
    ).stdout
    return [chemin for chemin in sortie.split("\0") if chemin]


def test_aucune_trace_processus_generatif() -> None:
    fautifs = []
    for chemin in fichiers_suivis():
        if chemin == CE_FICHIER:
            continue
        chemin_absolu = RACINE / chemin
        if not chemin_absolu.is_file():
            continue
        try:
            contenu = chemin_absolu.read_text(encoding="utf-8").lower()
        except (UnicodeDecodeError, OSError):
            continue
        for motif in MOTIFS_INTERDITS:
            if motif in contenu:
                fautifs.append(f"{chemin} : motif '{motif}'")

    assert not fautifs, "Trace de vocabulaire d'outil génératif : " + " | ".join(fautifs)
