"""Interdit toute trace de vocabulaire d'outil génératif et toute numérotation
interne d'étape dans les fichiers suivis.

Deux contrôles. Le premier porte sur un motif volontairement limité à trois
catégories de vocabulaire GÉNÉRIQUE et PUBLIC : noms de fournisseurs d'outils
génératifs, formules de co-signature automatique, formules d'attribution de
génération. Le second porte sur la numérotation interne d'étape de ce projet :
le mot désignant un bloc ou un lot de travail suivi d'un nombre, le mot
désignant une étape suivi d'un nombre (avec ou sans le préfixe bloc/lot), et
un identifiant de sous-étape combinant un chiffre et une lettre. Aucun de ces
motifs n'énumère un terme de la nomenclature interne autre que sa forme : un
test qui énumérerait ce vocabulaire interne serait lui-même la fuite qu'il
prétend empêcher. La détection de ce vocabulaire interne reste une revue
manuelle, plus large, exécutée avant chaque publication — ce test-ci est un
filet permanent, pas un remplacement.

Le motif d'étape seule (sans préfixe bloc/lot) a été élargi après qu'une revue
manuelle, pas ce filet, a trouvé trois notes de configuration référençant une
étape numérotée sans ce préfixe : le filet ne couvrait alors que la forme
préfixée. Quatre catégories d'emploi légitime du mot « étape » ou « passe »
existent dans le dépôt et doivent rester vertes après cet élargissement : la
clé `steps` du workflow CI (vocabulaire de la plateforme, ne contient pas le
mot « étape », hors motif par construction), une procédure réglementaire de
sortie citée dans la documentation (« étapes » n'y est jamais suivi d'un
chiffre, hors motif par construction), les commentaires décrivant un
algorithme à deux passes dans `generator/parcours.py` et son test (le mot
« passe », pas « étape », hors motif par construction), et ce fichier
lui-même (exclusion déclarée ci-dessous, seule catégorie qui ne doit sa
sécurité qu'à une exclusion explicite plutôt qu'à la forme du motif).

Ce fichier est nécessairement exclu de son propre parcours : il contient les
motifs recherchés en tant que données, pas en tant que trace. C'est
l'exclusion déclarée mentionnée ci-dessus.
"""

import re
import subprocess
from pathlib import Path

RACINE = Path(__file__).resolve().parent.parent
CE_FICHIER = Path(__file__).resolve().relative_to(RACINE).as_posix()

MOTIF_ETAPE = re.compile(r"\b(bloc|lot)\W{0,3}[0-9]", re.IGNORECASE)
MOTIF_ETAPE_SEULE = re.compile(r"\bétape[s]?\W{0,3}[0-9]", re.IGNORECASE)
MOTIF_SOUS_ETAPE = re.compile(r"\b[0-9]+\.[A-Za-z]\b")

MOTIFS_INTERDITS = [
    # Noms de fournisseurs d'outils génératifs
    "claude",
    "anthropic",
    "chatgpt",
    "openai",
    "gpt-3",
    "gpt-4",
    "gpt-5",
    "copilot",
    "gemini",
    "bard",
    "llama",
    "mistral ai",
    # Formules de co-signature automatique
    "co-authored-by",
    # Formules d'attribution de génération
    "generated by ai",
    "ai-generated",
    "ai generated",
    "ai-assisted",
    "ai assisted",
    "written by ai",
    "created with ai",
]


def fichiers_suivis() -> list[str]:
    sortie = subprocess.run(
        ["git", "-C", str(RACINE), "ls-files", "-z"],
        capture_output=True,
        check=True,
        text=True,
    ).stdout
    return [chemin for chemin in sortie.split("\0") if chemin]


def test_aucune_trace_processus_generatif() -> None:
    fautifs = []
    for chemin in fichiers_suivis():
        if chemin == CE_FICHIER:
            continue
        chemin_absolu = RACINE / chemin
        if not chemin_absolu.is_file():
            continue
        try:
            contenu = chemin_absolu.read_text(encoding="utf-8").lower()
        except (UnicodeDecodeError, OSError):
            continue
        for motif in MOTIFS_INTERDITS:
            if motif in contenu:
                fautifs.append(f"{chemin} : motif '{motif}'")

    assert not fautifs, "Trace de vocabulaire d'outil génératif : " + " | ".join(fautifs)


def test_aucune_numerotation_interne() -> None:
    fautifs = []
    for chemin in fichiers_suivis():
        # exclusion declaree : ce fichier porte les trois motifs ci-dessus comme donnees
        # de test, jamais comme trace reelle (voir le docstring du module).
        if chemin == CE_FICHIER:
            continue
        chemin_absolu = RACINE / chemin
        if not chemin_absolu.is_file():
            continue
        try:
            contenu = chemin_absolu.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for numero_ligne, ligne in enumerate(contenu.splitlines(), start=1):
            correspondance = (
                MOTIF_ETAPE.search(ligne)
                or MOTIF_ETAPE_SEULE.search(ligne)
                or MOTIF_SOUS_ETAPE.search(ligne)
            )
            if correspondance:
                fautifs.append(f"{chemin}:{numero_ligne} : '{correspondance.group(0)}'")

    assert not fautifs, "Numérotation interne d'étape : " + " | ".join(fautifs)
