-- Fichier produit mécaniquement depuis le registre des champs : ne pas
-- modifier à la main.

drop table if exists quarantaine.patients cascade;
create table quarantaine.patients (
    n_ipp text,
    nom text,
    nom_famille_1 text,
    nom_famille_2 text,
    sexe text,
    date_naissance text,
    type_piece_identite text,
    n_piece_identite text,
    etat_civil text,
    type_patient text,
    date_photo text,
    modifie_par text,
    cree_par text,
    date_attribution text,
    compagnie_assurance text,
    police text,
    n_assure text,
    profession text,
    num_inscription text,
    date_inscription text,
    type_domicile text,
    adresse text,
    code_postal text,
    etat text,
    ville text,
    quartier text,
    nationalite text,
    telephone_1 text,
    telephone_2 text,
    telephone_3 text,
    telephone_4 text,
    avertissements_sms text,
    email text,
    avertissements_email text,
    environnement text,
    nom_pere text,
    nom_mere text,
    etat_naissance text,
    ville_naissance text,
    pays_naissance text,
    quartier_naissance text,
    commentaire text,
    province text,
    exitus text,
    date_modification text,
    date_extraction text,
    rejet_motifs text,
    rejet_date_chargement timestamptz,
    rejet_partition text
);
