{#
    dim_patient : toutes les colonnes de int_patients (SCD 2, une ligne par version de fiche),
    plus trois colonnes de validité par fonction de fenêtre. Bornes semi-ouvertes : valide_de
    inclus, valide_jusqu_a exclu (NULL pour la version courante) -- exactement la sémantique
    de generator/patients.py::version_en_vigueur (dernière version dont la date d'extraction
    est <= au jour), le générateur et l'entrepôt racontent la même histoire.
#}

select
    n_ipp,
    nom,
    nom_famille_1,
    nom_famille_2,
    sexe,
    date_naissance,
    type_piece_identite,
    n_piece_identite,
    etat_civil,
    type_patient,
    date_photo,
    modifie_par,
    cree_par,
    date_attribution,
    compagnie_assurance,
    police,
    n_assure,
    profession,
    num_inscription,
    date_inscription,
    type_domicile,
    adresse,
    code_postal,
    etat,
    ville,
    quartier,
    nationalite,
    telephone_1,
    telephone_2,
    telephone_3,
    telephone_4,
    avertissements_sms,
    email,
    avertissements_email,
    environnement,
    nom_pere,
    nom_mere,
    etat_naissance,
    ville_naissance,
    pays_naissance,
    quartier_naissance,
    commentaire,
    province,
    exitus,
    date_modification,
    date_extraction,
    valide_de,
    lead(valide_de) over (partition by n_ipp order by valide_de) as valide_jusqu_a,
    lead(valide_de) over (partition by n_ipp order by valide_de) is null as est_courante
from (
    select
        n_ipp,
        nom,
        nom_famille_1,
        nom_famille_2,
        sexe,
        date_naissance,
        type_piece_identite,
        n_piece_identite,
        etat_civil,
        type_patient,
        date_photo,
        modifie_par,
        cree_par,
        date_attribution,
        compagnie_assurance,
        police,
        n_assure,
        profession,
        num_inscription,
        date_inscription,
        type_domicile,
        adresse,
        code_postal,
        etat,
        ville,
        quartier,
        nationalite,
        telephone_1,
        telephone_2,
        telephone_3,
        telephone_4,
        avertissements_sms,
        email,
        avertissements_email,
        environnement,
        nom_pere,
        nom_mere,
        etat_naissance,
        ville_naissance,
        pays_naissance,
        quartier_naissance,
        commentaire,
        province,
        exitus,
        date_modification,
        date_extraction,
        date_extraction as valide_de
    from {{ ref('int_patients') }}
) as versions
